---
# Apply Polymath Code Standard formatters and linters

# If other hooks are installed (like a commit-msg hook), the whole suite runs twice per commit.
# This limits it to only running the one time.
default_stages: [pre-commit]

repos:
  - repo: https://github.com/polymathrobotics/polymath_code_standard
    rev: v2.2.0
    hooks:
      - id: polymath-general
        exclude: package-lock.json
      - id: polymath-python
      - id: polymath-cpp
      - id: polymath-ros
      - id: polymath-shell
        exclude: .envrc
      - id: polymath-cmake
      - id: polymath-docker
      - id: polymath-markdown
      - id: polymath-xml
      - id: polymath-yaml
      - id: polymath-toml
      - id: polymath-json
        exclude: package-lock.json
      - id: polymath-copyright
        args: [--license, Apache-2.0, --copyright-org, 'Polymath Robotics, Inc.']
